// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByKNy4RmMA7q0tO0oQ_V47Jc3HGz5L-Q0',
    appId: '1:5371514451:web:fc63c3b12963a7b69340a6',
    messagingSenderId: '5371514451',
    projectId: 'rubrica-f3b3e',
    authDomain: 'rubrica-f3b3e.firebaseapp.com',
    databaseURL: 'https://rubrica-f3b3e-default-rtdb.firebaseio.com',
    storageBucket: 'rubrica-f3b3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHWMM1K4SPK6mKvAH8LVsqWZmyGbAMcsk',
    appId: '1:5371514451:android:310297b3c477a2d99340a6',
    messagingSenderId: '5371514451',
    projectId: 'rubrica-f3b3e',
    databaseURL: 'https://rubrica-f3b3e-default-rtdb.firebaseio.com',
    storageBucket: 'rubrica-f3b3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IFiA3IhqwFEpejMAU_u2X9YxX2U-TCk',
    appId: '1:5371514451:ios:9323a9ef70a3e8e99340a6',
    messagingSenderId: '5371514451',
    projectId: 'rubrica-f3b3e',
    databaseURL: 'https://rubrica-f3b3e-default-rtdb.firebaseio.com',
    storageBucket: 'rubrica-f3b3e.appspot.com',
    iosBundleId: 'com.example.rubrica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IFiA3IhqwFEpejMAU_u2X9YxX2U-TCk',
    appId: '1:5371514451:ios:9323a9ef70a3e8e99340a6',
    messagingSenderId: '5371514451',
    projectId: 'rubrica-f3b3e',
    databaseURL: 'https://rubrica-f3b3e-default-rtdb.firebaseio.com',
    storageBucket: 'rubrica-f3b3e.appspot.com',
    iosBundleId: 'com.example.rubrica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByKNy4RmMA7q0tO0oQ_V47Jc3HGz5L-Q0',
    appId: '1:5371514451:web:5b275b9b749ba39f9340a6',
    messagingSenderId: '5371514451',
    projectId: 'rubrica-f3b3e',
    authDomain: 'rubrica-f3b3e.firebaseapp.com',
    databaseURL: 'https://rubrica-f3b3e-default-rtdb.firebaseio.com',
    storageBucket: 'rubrica-f3b3e.appspot.com',
  );
}
